language: java
jdk:
- oraclejdk8
install: true
script:
- gradle zipMap
before_deploy:
- git config --global user.email "tripleabuilderbot@gmail.com" 
- git config --global user.name "tripleabuilderbot"
- export MAP_TAGGED_VERSION="$MAP_VERSION.$TRAVIS_BUILD_NUMBER"
- git tag $MAP_TAGGED_VERSION -a -m "$MAP_TAGGED_VERSION"
- git push -q https://$GITHUB_PERSONAL_ACCESS_TOKEN_FOR_TRAVIS@github.com/triplea-maps/$REPO_NAME --tags
deploy:
  provider: releases
  api_key:
    secure: YHXwx0XsZQ244X2XsO+YoraQZsQsVbxHt58W1NF1mPvGkVsZjpJD92QXlTyBDbfycMzyEAPSFIOUOlp68x8kK39BLpLoqZScBWhyaPsjMPdBlvmxEYDex2QWvMTaO6XLN+GXE99unyd0q3fn0X6zpimIwxj0ndr79eX7BCgD4xP2VcMot1SUVLLjO7Tleom/9ngdTOnfB95/CdURvlo8GV9z7haAMkgPyaxtgbqQKGXXIcPJyoYuWk6DxFZrWvNHBH0EilatcOvEafmVq3Z2FOXMg5c3N8p5PH/yeFafkdS5r8pY9Fzz32pbAJzp1v68jnL2MJsqOfrYelXjKTJ/nqP89Gf6AR3hyjAg+8Is7Lp0zmIBBzBzDjxpEXFdLvISaRnwTuh0Cp4ijj2qv1SrgL27932/A1jKKimlO4hvOGmjdxboq6+sKCYc2Hvygp82iNS9bPY/1siAKhFpd8dIx4wggE+qa8AgPeuZr0jzXv/e/hlbprBzrNUBr9sdIVLVJs8iCYyr1DTn9XeaDnlrYvQxW/SVRk1ThAiWXquTRVRB9eE6V1W8tphqkKjR0fNnCWb5hd/9dXnq1cO0RVTvLDyhqZKrRNYJfDAVcVY/2xGpKbfSzkdx/5FysJk4kDbVd0/h6MDHyUvzg1Zukw70fOjyFkPDPat6XJrp31Rzuho=
  file: "$REPO_NAME.zip"
  skip_cleanup: true
  prerelease: true
  on:
    tags: false
    all_branches: true
